In [1]:
import numpy as np

1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [2]:
a = np.linspace(12, 24, 12, dtype = np.int32, endpoint = False)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [3]:
a1 = a.reshape(int(a.size/6), 6)
a2 = a.reshape(int(a.size/4), 4)
a3 = a.reshape(int(a.size/3), 3)
a4 = a.reshape(int(a.size/2), 2)
a5 = a.reshape(int(a.size), 1)
a1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [4]:
a11 = a.reshape(int(a.size/6), -1)
a21 = a.reshape(int(a.size/4), -1)
a31 = a.reshape(-1, int(a.size/6))
a41 = a.reshape(-1, int(a.size/4))
a51 = a.reshape(-1, 1)
a51

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [5]:
# a51[0]   array([12])
# a[0]     12
# Все таки нет, при обращении по одному индексу в случае столбца мы получаем как раз одномерный массив, а не число
# a51.T array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])
# даже транспонированием одномерный массив из столбца не получается

5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [6]:
# b = np.random.normal(0.0, 1.0, [3, 4]) - и какое распределение надо? там так много вариантов, и каждый свой результат выдает
b = np.random.standard_normal([3, 4])
# b = np.random.uniform(0, 1, (3, 4))
b.flatten()

array([-0.293965  ,  0.86981269, -1.22205525, -1.03612474, -1.15869591,
        0.22605695,  0.09124402, -0.24381268,  0.84531986,  0.04244367,
       -0.18471603,  0.13914711])

6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [7]:
a = np.linspace(20, 0, 10, dtype = np.int32, endpoint = False)
a 

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [8]:
b = np.linspace([20], [1], 10, dtype = np.int32, endpoint = False, axis = 0) 
# Ни в чем, за исключением того, что а строка, а b столбец... и тут возникают сомнения, а является ли столбец двумерным или нет
# но в этом случае мы подавали на старт и конец массив из одного элемента
b 

array([[20],
       [18],
       [16],
       [14],
       [12],
       [10],
       [ 8],
       [ 6],
       [ 4],
       [ 2]])

8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [9]:
a = np.zeros((2, 2))
b = np.ones((3, 2))

In [10]:
v = np.concatenate((a, b), axis=0)
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [11]:
a = np.linspace(0, 12, 12, dtype = np.int32, endpoint = False)
A = a.reshape(4, 3)
At = A.T
B = np.dot(A, At)
# array([[  5,  14,  23,  32],
#        [ 14,  50,  86, 122],
#        [ 23,  86, 149, 212],
#        [ 32, 122, 212, 302]])
# матрица размером 4х4
# Вычислить то можно, но она быдет равна самой себе, так как матрица B симметрична относительно главной диагонали

10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [12]:
np.random.seed(42)

11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [13]:
C = np.random.randint(0, 16, 16, dtype = np.int32)

12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [14]:
C.resize([4, 4])
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [15]:
D = B + C

In [16]:
detD = np.linalg.det(D) 
rankD = np.linalg.matrix_rank(D) 
D_inv = np.linalg.inv(D) 
print('Определитель матрицы detD = ', detD)
print('Ранг матрицы rankD = ', rankD)
print('Обратная матрица D_inv = \n', D_inv)

Определитель матрицы detD =  -47196.0
Ранг матрицы rankD =  4
Обратная матрица D_inv = 
 [[ 0.13488431  0.07958302  0.17988813 -0.1812018 ]
 [-0.17149758  0.14009662  0.147343   -0.13687601]
 [-0.05758963  0.01220442 -0.20404272  0.14899568]
 [ 0.09668192 -0.08009153  0.05778032 -0.0194508 ]]


13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [17]:
D_inv[D_inv < 0] = 0
D_inv[D_inv > 0] = 1
D_inv

array([[1., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

In [18]:
E = np.where(D_inv == 1, B, C)
E

array([[  5,  14,  23,  14],
       [ 10,  50,  86,   4],
       [  6,  86,   2, 212],
       [ 32,  10, 212,   4]])